### PR TITLE
[2]Travis Support with flake8 & Dependency Check

### PR DESCRIPTION
**Pull request by hiteshgarg14**

### CODE REVIEW

**Comment by mileswwatkins** [comment]
@hiteshgarg14, were you able to set up the Travis CI service itself, beyond adding the configuration in here? I can't see any Travis builds yet.

**Comment by mileswwatkins** [comment]
I did some of the setup just now, as far as enabling the repo. But I don't think any builds have run yet, since I think builds only happen once the repo is "turned on" in the Travis CI web interface. Can you get a build to happen?

(Here's what I did:)

travis

**Comment by hiteshgarg14** [comment]
@mileswwatkins now it's working :)

https://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by mileswwatkins** [comment]
🎋

**Pull request merged**
