### PR TITLE
Minor improvements (Cont. #46)

### PR DESCRIPTION
**Pull request by hiteshgarg14**
As we have discussed:-

1. Admin can change status of patches.
2. View for admin to create a patch of alert type `error`.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
Looks good, but having some issues with the admin patch form:

- If I'm an admin, and want to create a patch for a _missing_ email, address, etc, how do I do that? In the current form, I'm required to put something in the `OLD VALUE` field.
- The form allowed me to submit a patch for an unidentified data type:
screen shot 2017-07-22 at 23 29 17
- Patches created by the admin should not need to be "Approved."

**Comment by hiteshgarg14** [comment]
> If I'm an admin, and want to create a patch for a missing email, address, etc, how do I do that?
all the missing issues are in `Data Quality Issues` section. so you have to go there and the form (and you can also provide multiple values for one legislator).

**Comment by hiteshgarg14** [comment]
> In the current form, I'm required to put something in the OLD VALUE field.

Yeah! this is because this is the form for `alert=error` ie, only for wrong values. (and if a value is wrong then there must be an old_value)

**Comment by hiteshgarg14** [comment]
> Patches created by the admin should not need to be "Approved."

all type of patches (missing values/wrong value) created by admin will be marked as `unreviewed`.

**Comment by mileswwatkins** [comment]
> all type of patches (missing values/wrong value) created by admin will be marked as unreviewed.

Admin-created patches should be approved-on-creation; only user-submitted patches should need to be reviewed.

**Comment by mileswwatkins** [comment]
> all the missing issues are in Data Quality Issues section. so you have to go there and the form (and you can also provide multiple values for one legislator).

Gotcha! Good point. When I make a change to a missing field (say, as the Admin user I add a missing email, in the Missing Emails view), does that create a patch? Or does that immediately update the database (and that's fine, because since the scraper isn't finding a value, then the admin-applied email address won't get overwritten by the scraper)?

**Comment by hiteshgarg14** [comment]
>Admin-created patches should be approved-on-creation; only user-submitted patches should need to be reviewed. Let me know if I'm thinking about this the wrong way, though :)

actually, james sir told me to mark them as unreviewed on slack [Link](https://openstates.slack.com/archives/G4M69PQPR/p1500047020120804)

**Comment by hiteshgarg14** [comment]
> does that create a patch? Or does that immediately update the database.

it creates a `unreviewed` patch for the same. [Link](https://github.com/openstates/admintools/pull/28#issuecomment-314912550)

**Comment by mileswwatkins** [comment]
Alright, I think that this PR is cleared, too, then. Just waiting on https://github.com/openstates/admintools/pull/44.

cc @jamesturk

**Pull request merged**
