### PR TITLE
[3]More Info in State Specific Pages

### LINKED ISSUE #3: implement state-specific status pages
after #1

### PR DESCRIPTION
**Pull request by hiteshgarg14**
For now, there is not much information added to individual pages. but taking inspiration from Billy I have done some changes.
For Bills Section, I am not sure what else to do. In Billy, we have info about `Bill Counts`, `Bill Types`, `Actions by Type`, `Actions by Actor`, `Actions by Month`. If this data is important then we can show that. I am not sure about its importance. 

Here are some thoughts about future of state-specific pages

1. In future admin may want to know about activity status of any particular legislator, organization, bill, vote event like 
   - how many notification subscribers we have for a legislator.
   - how many users are following a particular bill on openstates.org
   - what is the view count of a particular state on openstates.org means how many people are interested in a particular state? this will also help us to address data quality issues. means we should focus on the issues for a more interested state.
   - etc.

closes #3

### CODE REVIEW

**Comment by mileswwatkins** [comment]
This all seems functional, but I agree with you @hiteshgarg14 that we haven't really thought out what the state- or session-specific pages ought to include or if they should exist in their Billy-like form. Let's talk about this a bit tomorrow, and maybe stop back and consider direction a bit.

**Comment by mileswwatkins** [comment]
Feedback mostly c/o @jamesturk:

#### Overall:

- The admin tool shouldn't be about _browsing_ the data, as much as it should be about 1) identifying problems and 2) being able to fix (or at least diagnose) them manually. So, for example, the table of legislators with missing photos should have a way for the admin to type in the photo URLs directly; the table of VoteEvents with bad counts should include the two (different) counts and a link to the source URL for that VoteEvent, so that the admin can determine what the problem may be; if a committee has no memberships, include a button to delete that committee from the database if the admin determines that it doesn't exist anymore; if a voter is unmatched, drive the user towards the name matching tool; etc. Basically, the goal is to make all of these lists as actionable as possible.
- We need to determine how these admin interface edits are applied to the database, and how they can stick around between scrapes (ie, not just get overwritten!). _This is a blocker!_ See https://github.com/openstates/admintools/issues/23. So a lot of the above, needed functionality cannot be added right now.

#### UX:

- The warning and error counts on the state page should always be expanded, never hidden; there's not much of a use-case for having them hidden. Ie,

screen shot 2017-07-04 at 13 41 38

not 

screen shot 2017-07-04 at 13 41 30

- Furthermore, on the state pages, the issue types that have a count of `0` could be hidden altogether; it's likely that the administrators would know all the data quality types, so there's no reason to show a type if there are no problems of that kind.
- The lists of individual entities shouldn't contain their OCD ID, since that's not necessarily immediately useful (if anything, just include links to their Pupa admin pages, if they exist).
- Likewise, there's no need to display row number on the leftmost column of those lists.

#### Bugs:

- The text searches in lists (eg, for `admintools/Alabama/person/missing-email`) appear to only search from the beginning of the string, not a full substring search of the name/value. Eg, `Alan Boothe` is matched by a search of `Al` but not of `Bo`.

#### Data quality generation:

- Except in rare cases, the Legislature isn't expected to have memberships; suppress that error when creating the data quality issues.
- Does Pupa allow VoteEvents with a missing bill? It may be in the spec, but not in Pupa. If it's not in Pupa, we could consider deleting this data quality issue.

**Comment by hiteshgarg14** [comment]
The Coverage (with `mergetool test`) is 99%.

Actually, I made some changes in the `python-opencivicdata` repo locally. because some links are broken due to splitting the repo into `core` and `legislative` apps.
So should I create a PR on that repo for the changes I have done locally? (otherwise `test` will fail for them)(these are some minor changes though)

**Comment by hiteshgarg14** [comment]
> Does Pupa allow VoteEvents with a missing bill? It may be in the spec, but not in Pupa. If it's not in Pupa, we could consider deleting this data quality issue.

I think yes, Pupa allow VoteEvents with a missing bill { [Link](https://github.com/opencivicdata/pupa/blob/master/pupa/scrape/vote_event.py#L15) and `null=True` at [Link](https://github.com/opencivicdata/python-opencivicdata/blob/master/opencivicdata/legislative/models/vote.py#L26) }

**Comment by hiteshgarg14** [comment]
> Likewise, there's no need to display row number on the leftmost column of those lists.

actually, I put it there because we have `search button` on the same column. so instead of keeping it blank, I put row count there.
Should I remove the `search button` from there as we can press `Enter` to search and this page is not for general users?

**Pull request merged**
