### PR TITLE
Status Page with Data Quality Issues Section for State Specific Page

### PR DESCRIPTION
**Pull request by hiteshgarg14**
Added `Jurisdiction` in `DataQualityIssue` Model Class to make individual queries fast and easy.

### CODE REVIEW

**Comment by hiteshgarg14** [comment]
@mileswwatkins @jamesturk ready for review :+1:

**Comment by jamesturk** [comment]
A few initial thoughts:

1) it is looking pretty good!  I'm impressed w/ how much information is visible when I run this
2) you might want to install django_debug_toolbar :) it's really helpful for looking at how many queries are made, etc.
3) we can hash out the specific design later, but I wonder if using emoji for things like ❌  and ✅ would be cleaner 

4) Looking at this, I think that the Reports might not be the most efficient way to go.  If you run aggregate queries (https://docs.djangoproject.com/en/1.11/topics/db/aggregation/) you can actually get the same information on the fly in fewer queries:

```
# a query like:
Jurisdiction.objects.filter(dataquality_issues__content_type=person_ct).annotate(person_issues=Count('dataquality_issues')).order_by('name')
# is quite fast and gives the same values used in the first column of overview

#and then there's the option of using one single query for the whole table:
all_counts = DataQualityIssue.objects.values('jurisdiction', 'issue').annotate(Count('issue'))
# which returns a bunch of data like:
{'jurisdiction': 'ocd-jurisdiction/country:us/state:wi/government', 'issue': 'bill-no-sponsors', 'issue__count': 17}
```

**Comment by hiteshgarg14** [comment]
I have gone through some possible techniques like:-

1.  344 Queries in ~1080 ms
```
queryset = DataQualityIssue.objects.values('jurisdiction', 'issue',
                                               'alert')
    upstream = ['person', 'organization', 'membership', 'bill', 'vote']
    for jur in all_jurs:
        reports = {}
        reports['name'] = jur.name
        for item in upstream:
            reports[item] = {'warning': queryset.filter(jurisdiction=jur, alert='warning',
                                                        issue__istartswith=item).count(),
                             'error': queryset.filter(jurisdiction=jur, alert='error',
                                                      issue__istartswith=item).count()
```

2.  344 Queries in ~1220 ms
```
queryset = DataQualityIssue.objects.values('jurisdiction', 'issue',
                                               'alert').annotate(Count('issue'))
    upstream = ['person', 'organization', 'membership', 'bill', 'vote']
    for jur in all_jurs:
        reports = {}
        reports['name'] = jur.name
        for item in upstream:
            reports[item] = {'warning': queryset.filter(jurisdiction=jur, alert='warning',
                                                        issue__istartswith=item).aggregate(Sum('issue__count')),
                             'error': queryset.filter(jurisdiction=jur, alert='error',
                                                      issue__istartswith=item).aggregate(Sum('issue__count'))
```

3. 209 Queries in ~232 ms  (latest pushed code)
```
DataQualityIssue.objects.values('jurisdiction', 'issue', 'alert').annotate(Count('issue'))
```
BUT in 3rd approach CPU Time increases. (does it related to hardware configurations? If so then I believe that it's not an issue since my laptop is of lower configuration and on AWS we have better hardware configurations.) 

4. Specific design for each error no longer supported.
5.  django_debug_toolbar installed. :)

**Comment by mileswwatkins** [comment]
Finally got it working #neverdreamed

Thoughts on the interface and UX; clearly I shouldn't be giving Django advice ;)

Regarding the dashboard:

- In the "Last Run" column of the main dashboard, is there any way to hook in [Bobsled-like information](http://bobsled.openstates.org/) on _not only the most recent run_, but instead the most recent _several_ runs? Might be nice to know if a scraper has been down for a few days, or just one. Alternatively, also happy to have that information only in Bobsled (or if this info isn't available to the OCD database, not sure where it's stored).
- Agreeing with James, I really like the simplicity and information density of the main dashboard layout!
- Is there a good way to left-align all of the warning counts, and all of the error counts? Might make the page a bit easier to parse, but at the same time I could see an issue with adding _another_ level of complexity to the layout grid/table. What do you think, worth it or not?

So far, the subpages seem less streamlined and thoroughly-designed in general, but we can improve them going forward! Some initial thoughts, what do you two think of these?

- I'd prefer to see sortable, paginated lists rather than a large set of buttons, since it's more structured and easier to suss out patterns and have a reasonable page length (since some states have thousands of warnings)
- It'd also be nice to have some immediately-provided context for the warnings/errors when you drill down. For example, for "Bad Counts," what is the _expected_ count and what's the _observed_ count that seems bad? What's the name of the "Unmatched Person"? Maybe we could have these human-readable error messages as another row in the database table, or maybe that's not necessary.
- Finally, another tweak could be to add a link from a particular data type's error page to the related scraper code on GitHub; from Arizona Bills page in `admintools`, you could add a button to access `https://github.com/openstates/openstates/blob/master/openstates/az/bills.py`, and/or show the raw code in-page or something

---

Larger thought:

What if all of the error/warning-type lists were just links to querystring-filtered Django admin views? That is, if you drilled down to persons with "Missing Image," you won't be shown a list in the `admintools` app; instead, you'd be forwarded to `/admin/legislative/person/?image__isnull=True`.

Strengths:

- We get more of our views for free, minimizing code upkeep and letting us focus our development on the fewer core views of the `admintools` app
- The admin's tables are already pretty nice, and should serve most of our purposes

Weaknesses:

- Not too familiar with Django's query string language; some of our filters may be impossible to write as query strings?
- Doubling processing, insofar as we've already made this database query when doing `python manage.py import all`. But since admins are such a small part of our userbase, I don't think this is a problem.
- We don't get to easily add extra warning-/error-note fields to the tables, for context as to what could be wrong

**Comment by hiteshgarg14** [comment]
Here are some of my thoughts  :smiley:

1. All the Run Info (success/failure) is getting stored in `RunPlan` Pupa Model Class. so if we want then we can fetch data from there and can display the information as you described.
2. I have also struggled with the padding problem but didn't find any appropriate solution. Initially, I tried some layouts like,
   - Left align all errors & warnings. 
   - divide each column into two sub-columns for errors and warnings and display separate status for them (but that will increase the complexity of the table)
   -  the third one, which we have now. (but not good as it actually can be)
3.  Yeah! it's not a good idea to list all of them on a single page without pagination. we can go for pagination with a search bar. but why I did like that? the answer to this question is that because I thought admin-user is only interested in searching for a particular bill/org etc. so we can use `ctrl+F` to directly find things on a single page. I believe that the best solution of this is to link it with Django-admin panel because all the required info is there. but at the same time, I concern about speed. because I believe that a query from `dataquality_issue` table will be fast than query from `bills` etc. tables. 
    - sorry, but I didn't get on which basis we want to filter results. means if we look at admin panel then there is only filter by jurisdiction. for example. if a bill has a data quality issue then on which basis we want to sort it? and also I didn't get what is `expected count` here.
4. it's a good idea to link it with the respective GitHub page. because later in future we may want to open data quality issue section for other users. so if anyone wants to solve the problem then the user can directly take a look at the code.

Thanks!

**Comment by hiteshgarg14** [comment]
Let me know if we need anything else in filters.

**Comment by jamesturk** [comment]
I'm 👍 for a merge on this

**Comment by mileswwatkins** [comment]
Yup, let's get this branch merged in soon so that we can have smaller PRs that're easier to review :D

**Pull request merged**
